# config/packages/monolog.yaml
monolog:
  channels: ['app']

  handlers:
    main:
      type: rotating_file
      max_files: 7
      path: '%kernel.logs_dir%/%kernel.environment%.log'
      level: debug
      channels: ['!event']
      formatter: monolog.formatter.line
      include_stacktraces: true

    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!console"]
      formatter: monolog.formatter.line

    error:
      type: rotating_file
      max_files: 7
      path: '%kernel.logs_dir%/error.log'
      level: error
      channels: ['!event']
      formatter: monolog.formatter.line
      include_stacktraces: true

    transfer:
      type: rotating_file
      max_files: 7
      path: '%kernel.logs_dir%/transfer.log'
      level: info
      channels: ['app']
      formatter: monolog.formatter.line
      include_stacktraces: true