# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER_ID: ${MY_UID:-637}
        GROUP_ID: ${MY_GID:-48}
    container_name: bank_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - infra_net
    user: "${MY_UID}:${MY_GID}"

  nginx:
    image: nginx:alpine
    container_name: bank_nginx
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - infra_net

  redis:
    image: redis:7-alpine
    container_name: bank_redis
    ports:
      - "6379:6379"
    networks:
      - infra_net


  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: rakesh
      MYSQL_PASSWORD: rakesh
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - infra_net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: rakesh
      PMA_PASSWORD: rakesh
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - infra_net

  php:
    image: php:8.2-apache
    container_name: php8
    volumes:
      - ./php-app:/var/www/html
    ports:
      - "8081:80"
    restart: always
    networks:
      - infra_net

volumes:
  mariadb_data:
  es_data:

networks:
  infra_net:
    external: true
